stages:
  - test
  - build

cover:
  stage: test
  script:
  - ln -s `pwd` $GOPATH/src/gitlab.quantdo.cn/yuanyang/autoorder
  - echo GOROOT=$GOROOT
  - echo GOPATH=$GOPATH
  - cd orderbook
  - go test -cover