stages:
  - test
  - build

cover:
  stage: test
  script:
  - PROJECT_PATH=$GOPATH/src/gitlab.quantdo.cn/yuanyang/autoorder
  - mkdir -p `dirname $PROJECT_PATH`
  - ln -s `pwd` $PROJECT_PATH
  - echo GOROOT=$GOROOT
  - echo GOPATH=$GOPATH
  - go test -cover `go list ./...`